### ISSUE TITLE
Can't run demo

### ISSUE THREAD

**Issue by Dekermanjian** [voila-dashboards/voici#113]
I am unable to get the demo to build following the instructions in the README of this repo. 

I am getting the following error:
```
InvalidArchiveError('Error with archive C:\\Users\\Username\\miniconda3\\pkgs\\pillow-10.2.0-hf51ec75_0.tar.bz2.  You probably need to delete and re-do)
InvalidArchiveError('Error with archive C:\\Users\\Username\\miniconda3\\pkgs\\ipython-8.22.2-py311had7285e_0.tar.bz2.  You probably need to delete and)
InvalidArchiveError('Error with archive C:\\Users\\Username\\miniconda3\\pkgs\\pandas-1.5.3-h5aab7b2_0.tar.bz2.  You probably need to delete and re-dow)
InvalidArchiveError('Error with archive C:\\Users\\Username\\miniconda3\\pkgs\\python-3.11.3-h_hash_24_cpython.tar.bz2.  You probably need to delete an)

[VoiciBuildApp] ERROR | [lite] [post_build] [jupyterlite-xeus] [ERR] Command '['C:\\Users\\Username\\miniconda3\\condabin\\conda.BAT', 'install', '--yes', '--prefix', WindowsPath('C:/Users/JONATH~1/AppData/Local/Temp/tmpqx1g5bpx/env/envs/voici'), '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'conda-forge', 'xeus-python', 'pandas', 'bqplot', 'ipycanvas', 'ipywidgets']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\doit_cmd.py", line 294, in run
    return command.parse_execute(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\cmd_base.py", line 570, in execute
    return self._execute(**exec_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\runner.py", line 254, in run_all
    self.run_tasks(task_dispatcher)
  File "C:\Users\Username\miniconda3\envs\adhoc\Lib\site-packages\doit\runner.py", line 213, in run_tasks
    node = task_dispatcher.generator.send(node)

```

Any help would be appreciated.

**Comment by martinRenou** [comment]
Thanks for opening an issue. Do you see other errors prior to this?

**Comment by trungleduc** [comment]
it looks like an issue of `jupyterlite-xeus` on Windows

**Comment by jgunstone** [comment]
not sure if its related but the past few times I've tried to run the live demo linked in the README get a permanent spin

<img width="918" alt="image" src="https://github.com/voila-dashboards/voici/assets/21370980/2cc92fd3-6f73-4606-a45d-e3ec74cce342">

**Comment by martinRenou** [comment]
@jgunstone can you try from a private window? Just to make sure you're not hitting cache

**Comment by trungleduc** [comment]
@parthi2929 `jupyterlite_xeus` does not work well with Windows yet (https://github.com/jupyterlite/xeus/pull/56)

**Comment by jgunstone** [comment]
> @jgunstone can you try from a private window? Just to make sure you're not hitting cache

this sorted it - thanks

**Comment by martinRenou** [comment]
@parthi2929 are you able to run `C:\\Users\\PC-NAME\\miniconda3\\condabin\\conda.BAT create --yes --prefix 'C:/Users/USER~1/AppData/Local/Temp/tmpzx8z5mya/env/envs/voici' -c https://repo.mamba.pm/emscripten-forge -c conda-forge` on this machine and show us the output?

**Comment by parthi2929** [comment]
@martinRenou Please find it below.. 

```
The system cannot find the path specified.
Channels:
 - https://repo.mamba.pm/emscripten-forge
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\USER~1\AppData\Local\Temp\tmpzx8z5mya\env\envs\voici



Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate C:\Users\USER~1\AppData\Local\Temp\tmpzx8z5mya\env\envs\voici
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by parthi2929** [comment]
If could be helpful, my `where conda` is 

```
$ where conda
C:\Users\PC-NAME\miniconda3\condabin\conda.bat
C:\Users\PC-NAME\miniconda3\Library\bin\conda.bat
C:\Users\PC-NAME\miniconda3\Scripts\conda.exe
```
