### ISSUE TITLE
Can not run demo on Windows with micromamba

### ISSUE THREAD

**Issue by Madnex** [voila-dashboards/voici#125]
## Description

I am having issues running the demo on Windows.

## Reproduce
Follow the steps described for the demo.

## Expected behavior

Demo should run.

## Context

- voila version 0.7.0
- Operating System and version: Windows 10
- Browser and version: Edge

<details><summary>Command Line Output</summary>
<pre>
Linking emscripten-abi-3.1.45-h267e887_29
Linking pillow-10.3.0-hf51ec75_0
warning  libmamba Invalid package cache, file 'C:\Users\FQ19OO\AppData\Local\Temp\tmpcho52_pw\env\pkgs\pillow-10.3.0-hf51ec75_0\bin\python.bak' is missing
error    libmamba Cannot find a valid extracted directory cache for 'pillow-10.3.0-hf51ec75_0.tar.bz2'
critical libmamba Package cache error.
</pre>
</details>

I did not manage to get it running with `micromamba`. It is always having issues finding the python instance somehow. Running an environment with `micromamba`is working fine though.

**Comment by jtpio** [comment]
Thanks @Madnex for the report :+1: 

cc @DerThorsten @martinRenou if you have any hint on what could be the cause of the issue.

**Comment by DerThorsten** [comment]
> ## Description
> I am having issues running the demo on Windows.
> 
> ## Reproduce
> Follow the steps described for the demo.
> 
> ## Expected behavior
> Demo should run.
> 
> ## Context
> * voila version 0.7.0
> * Operating System and version: Windows 10
> * Browser and version: Edge
> 
> Command Line Output
> Linking emscripten-abi-3.1.45-h267e887_29
> Linking pillow-10.3.0-hf51ec75_0
> warning  libmamba Invalid package cache, file 'C:\Users\FQ19OO\AppData\Local\Temp\tmpcho52_pw\env\pkgs\pillow-10.3.0-hf51ec75_0\bin\python.bak' is missing
> error    libmamba Cannot find a valid extracted directory cache for 'pillow-10.3.0-hf51ec75_0.tar.bz2'
> critical libmamba Package cache error.
> I did not manage to get it running with `micromamba`. It is always having issues finding the python instance somehow. Running an environment with `micromamba`is working fine though.


not really sure why `bin\python.bak` is in the package in the first place.
I assume we could remove this file from the pillow build

**Comment by Madnex** [comment]
Thanks, the error disappeared but now I am getting this error instead :/ 

<details>
  <summary>Error messages</summary>
  
  ```console
Linking emscripten-abi-3.1.45-h267e887_29
Linking pillow-10.3.0-py311h1bb38f8_1
Linking pyjs-2.1.0-py311hd5f3483_7
[VoiciBuildApp] ERROR | [lite] [post_build] [jupyterlite-xeus] [ERR] Command '['C:\\Users\\FQ19OO\\micromamba\\condabin\\micromamba.BAT', 'create', '--yes', '--no-pyc', '--root-prefix', WindowsPath('C:/Users/FQ19OO/AppData/Local/Temp/tmpjv4edaa3/env'), '--name', 'voici', '--platform=emscripten-wasm32', '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'conda-forge', 'xeus-python', 'pandas', 'bqplot', 'ipycanvas', 'ipywidgets', 'emscripten-abi=3.1.45']' returned non-zero exit status 3221225477.
Traceback (most recent call last):
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\doit_cmd.py", line 294, in run
    return command.parse_execute(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\cmd_base.py", line 570, in execute
    return self._execute(**exec_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\runner.py", line 254, in run_all
    self.run_tasks(task_dispatcher)
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\runner.py", line 213, in run_tasks
    node = task_dispatcher.generator.send(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\control.py", line 629, in _dispatcher_generator
    next_step = node.step()
                ^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\control.py", line 336, in step
    return next(self.generator)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\control.py", line 345, in _func
    for value in decorated(*args, **kwargs):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\control.py", line 473, in _add_task
    new_tasks = generate_tasks(to_load, task_gen, ref.__doc__)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\loader.py", line 390, in generate_tasks
    for task_dict, x_doc in flat_generator(gen_result, gen_doc):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\doit\loader.py", line 27, in flat_generator
    for item in gen:
                ^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_core\manager.py", line 138, in _delayed_gather
    yield from _gather()
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_core\manager.py", line 131, in _gather
    raise error
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_core\manager.py", line 123, in _gather
    for task in getattr(addon, attr)(self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_xeus\add_on.py", line 124, in post_build
    self.create_prefix()
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_xeus\add_on.py", line 148, in create_prefix
    create_conda_env_from_env_file(root_prefix, yaml_content, env_file.parent)
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_xeus\create_conda_env.py", line 55, in create_conda_env_from_env_file
    create_conda_env_from_specs(
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_xeus\create_conda_env.py", line 71, in create_conda_env_from_specs
    _create_conda_env_from_specs_impl(
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\site-packages\jupyterlite_xeus\create_conda_env.py", line 107, in _create_conda_env_from_specs_impl
    subprocess_run(
  File "C:\Users\FQ19OO\micromamba\envs\test_env\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\FQ19OO\\micromamba\\condabin\\micromamba.BAT', 'create', '--yes', '--no-pyc', '--root-prefix', WindowsPath('C:/Users/FQ19OO/AppData/Local/Temp/tmpjv4edaa3/env'), '--name', 'voici', '--platform=emscripten-wasm32', '-c', 'https://repo.mamba.pm/emscripten-forge', '-c', 'conda-forge', 'xeus-python', 'pandas', 'bqplot', 'ipycanvas', 'ipywidgets', 'emscripten-abi=3.1.45']' returned non-zero exit status 3221225477.
  ```
  
</details>

**Comment by Madnex** [comment]
No, sorry. Couldn't use it in the end :/
